/*
 * This file is autogenerated, see util/job-gen.py and dat/jobs/ for more info.
 *
 * Entry format:
 *   row 0: job enum
 *   row 1: two-letter abbreviation, name
 *   row 2: starting strength, intelligence, dexterity
 *   row 3: recommended species for character selection
 *   row 4: starting equipment (not including ration or weapon/ammo)
 *   row 5: weapon choice before game start
 *   row 6: starting skills
 */

static const map<job_type, job_def> job_data =
{

{ JOB_ABYSSAL_KNIGHT, {
    "AK", "Abyssal Knight",
    4, 4, 4,
    { SP_HILL_ORC, SP_SPRIGGAN, SP_TROLL, SP_MERFOLK, SP_BASE_DRACONIAN, SP_DEMONSPAWN },
    { "leather armour" },
    weapon_choice::plain,
    { { SK_ARMOUR, 1 }, { SK_DODGING, 1 }, { SK_FIGHTING, 3 }, { SK_INVOCATIONS, 2 }, { SK_WEAPON, 2 } },
} },


{ JOB_AIR_ELEMENTALIST, {
    "AE", "Air Elementalist",
    0, 7, 5,
    { SP_DEEP_ELF, SP_NAGA, SP_TENGU, SP_BASE_DRACONIAN, SP_VINE_STALKER },
    { "robe", "book of Air" },
    weapon_choice::none,
    { { SK_AIR_MAGIC, 3 }, { SK_CONJURATIONS, 1 }, { SK_DODGING, 2 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_ARCANE_MARKSMAN, {
    "AM", "Arcane Marksman",
    2, 5, 5,
    { SP_FORMICID, SP_DEEP_ELF, SP_KOBOLD, SP_SPRIGGAN, SP_TROLL, SP_CENTAUR },
    { "robe", "book of Debilitation" },
    weapon_choice::ranged,
    { { SK_DODGING, 2 }, { SK_FIGHTING, 1 }, { SK_HEXES, 3 }, { SK_SPELLCASTING, 1 }, { SK_WEAPON, 2 } },
} },


{ JOB_ARTIFICER, {
    "Ar", "Artificer",
    4, 3, 5,
    { SP_DEEP_DWARF, SP_HALFLING, SP_KOBOLD, SP_SPRIGGAN, SP_BASE_DRACONIAN, SP_DEMONSPAWN },
    { "short sword", "leather armour", "wand of flame charges:15", "wand of enslavement charges:15", "wand of random effects charges:15" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_EVOCATIONS, 3 }, { SK_FIGHTING, 1 }, { SK_STEALTH, 1 }, { SK_WEAPON, 1 } },
} },


{ JOB_BERSERKER, {
    "Be", "Berserker",
    9, -1, 4,
    { SP_HILL_ORC, SP_HALFLING, SP_OGRE, SP_MERFOLK, SP_MINOTAUR, SP_GARGOYLE, SP_DEMONSPAWN },
    { "animal skin" },
    weapon_choice::plain,
    { { SK_DODGING, 2 }, { SK_FIGHTING, 3 }, { SK_WEAPON, 3 } },
} },


{ JOB_BRIGAND, {
    "Br", "Brigand",
    3, 3, 6,
    { SP_HILL_ORC, SP_HALFLING, SP_OGRE, SP_MERFOLK, SP_MINOTAUR, SP_GARGOYLE, SP_DEMONSPAWN },
    { "dagger plus:2", "robe", "cloak", "dart ego: poisoned q:8", "dart ego:curare q:2" },
    weapon_choice::plain,
    { { SK_DODGING, 1 }, { SK_FIGHTING, 2 }, { SK_STEALTH, 4 }, { SK_THROWING, 2 }, { SK_WEAPON, 2 } },
} },


{ JOB_CHAOS_KNIGHT, {
    "CK", "Chaos Knight",
    4, 4, 4,
    { SP_HILL_ORC, SP_TROLL, SP_CENTAUR, SP_MERFOLK, SP_BASE_DRACONIAN, SP_MINOTAUR, SP_DEMONSPAWN },
    { "leather armour plus:2" },
    weapon_choice::plain,
    { { SK_ARMOUR, 1 }, { SK_DODGING, 1 }, { SK_FIGHTING, 3 }, { SK_WEAPON, 3 } },
} },


{ JOB_CONJURER, {
    "Cj", "Conjurer",
    0, 7, 5,
    { SP_DEEP_ELF, SP_NAGA, SP_TENGU, SP_BASE_DRACONIAN, SP_DEMIGOD },
    { "robe", "book of Conjurations" },
    weapon_choice::none,
    { { SK_CONJURATIONS, 4 }, { SK_DODGING, 2 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_DELVER, {
    "De", "Delver",
    4, 2, 6,
    { SP_FELID, SP_SPRIGGAN, SP_KOBOLD, SP_VAMPIRE, SP_GNOLL },
    { "leather armour", "scroll of fog", "scroll of magic mapping", "scroll of fear", "potion of haste", "wand of digging charges:3" },
    weapon_choice::plain,
    { { SK_DODGING, 2 }, { SK_FIGHTING, 3 }, { SK_STEALTH, 5 }, { SK_WEAPON, 2 } },
} },


{ JOB_EARTH_ELEMENTALIST, {
    "EE", "Earth Elementalist",
    0, 7, 5,
    { SP_DEEP_ELF, SP_DEEP_DWARF, SP_SPRIGGAN, SP_GARGOYLE, SP_DEMIGOD, SP_GHOUL, SP_OCTOPODE },
    { "robe", "book of Geomancy" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_EARTH_MAGIC, 3 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 }, { SK_TRANSMUTATIONS, 1 } },
} },


{ JOB_ENCHANTER, {
    "En", "Enchanter",
    0, 7, 5,
    { SP_DEEP_ELF, SP_FELID, SP_SPRIGGAN, SP_KOBOLD, SP_NAGA, SP_VAMPIRE },
    { "dagger plus:1", "robe", "book of Maledictions" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_HEXES, 3 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 3 }, { SK_WEAPON, 1 } },
} },


{ JOB_FIGHTER, {
    "Fi", "Fighter",
    8, 0, 4,
    { SP_DEEP_DWARF, SP_HILL_ORC, SP_TROLL, SP_MINOTAUR, SP_GARGOYLE, SP_CENTAUR },
    { "scale mail", "shield", "potion of might" },
    weapon_choice::good,
    { { SK_ARMOUR, 3 }, { SK_FIGHTING, 3 }, { SK_SHIELDS, 3 }, { SK_WEAPON, 2 } },
} },


{ JOB_FIRE_ELEMENTALIST, {
    "FE", "Fire Elementalist",
    0, 7, 5,
    { SP_DEEP_ELF, SP_HILL_ORC, SP_NAGA, SP_TENGU, SP_DEMIGOD, SP_GARGOYLE },
    { "robe", "book of Flames" },
    weapon_choice::none,
    { { SK_CONJURATIONS, 1 }, { SK_DODGING, 2 }, { SK_FIRE_MAGIC, 3 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_GLADIATOR, {
    "Gl", "Gladiator",
    6, 0, 6,
    { SP_DEEP_DWARF, SP_HILL_ORC, SP_MERFOLK, SP_MINOTAUR, SP_GARGOYLE, SP_CENTAUR },
    { "leather armour", "helmet", "throwing net q:3" },
    weapon_choice::good,
    { { SK_DODGING, 3 }, { SK_FIGHTING, 2 }, { SK_THROWING, 2 }, { SK_WEAPON, 3 } },
} },


{ JOB_HUNTER, {
    "Hu", "Hunter",
    4, 3, 5,
    { SP_HILL_ORC, SP_HALFLING, SP_KOBOLD, SP_OGRE, SP_TROLL, SP_CENTAUR },
    { "short sword", "leather armour" },
    weapon_choice::ranged,
    { { SK_DODGING, 2 }, { SK_FIGHTING, 2 }, { SK_STEALTH, 1 }, { SK_WEAPON, 4 } },
} },


{ JOB_ICE_ELEMENTALIST, {
    "IE", "Ice Elementalist",
    0, 7, 5,
    { SP_DEEP_ELF, SP_MERFOLK, SP_NAGA, SP_BASE_DRACONIAN, SP_DEMIGOD, SP_GARGOYLE },
    { "robe", "book of Frost" },
    weapon_choice::none,
    { { SK_CONJURATIONS, 1 }, { SK_DODGING, 2 }, { SK_ICE_MAGIC, 3 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_MONK, {
    "Mo", "Monk",
    3, 2, 7,
    { SP_DEEP_DWARF, SP_HILL_ORC, SP_TROLL, SP_CENTAUR, SP_MERFOLK, SP_GARGOYLE, SP_DEMONSPAWN },
    { "robe" },
    weapon_choice::plain,
    { { SK_DODGING, 3 }, { SK_FIGHTING, 3 }, { SK_STEALTH, 2 }, { SK_WEAPON, 3 } },
} },


{ JOB_NECROMANCER, {
    "Ne", "Necromancer",
    0, 7, 5,
    { SP_DEEP_ELF, SP_DEEP_DWARF, SP_HILL_ORC, SP_DEMONSPAWN, SP_MUMMY, SP_VAMPIRE },
    { "robe", "book of Necromancy" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_NECROMANCY, 4 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_SKALD, {
    "Sk", "Skald",
    3, 5, 4,
    { SP_HALFLING, SP_CENTAUR, SP_MERFOLK, SP_BASE_DRACONIAN, SP_VAMPIRE },
    { "leather armour", "book of Battle" },
    weapon_choice::plain,
    { { SK_ARMOUR, 1 }, { SK_CHARMS, 3 }, { SK_DODGING, 2 }, { SK_FIGHTING, 2 }, { SK_SPELLCASTING, 2 }, { SK_WEAPON, 2 } },
} },


{ JOB_SUMMONER, {
    "Su", "Summoner",
    0, 7, 5,
    { SP_DEEP_ELF, SP_HILL_ORC, SP_VINE_STALKER, SP_MERFOLK, SP_TENGU, SP_VAMPIRE },
    { "robe", "book of Callings" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 }, { SK_SUMMONINGS, 4 } },
} },


{ JOB_TRANSMUTER, {
    "Tm", "Transmuter",
    2, 5, 5,
    { SP_NAGA, SP_MERFOLK, SP_BASE_DRACONIAN, SP_DEMIGOD, SP_DEMONSPAWN, SP_TROLL },
    { "arrow q:12", "robe", "book of Changes" },
    weapon_choice::none,
    { { SK_DODGING, 2 }, { SK_FIGHTING, 1 }, { SK_SPELLCASTING, 2 }, { SK_TRANSMUTATIONS, 2 }, { SK_UNARMED_COMBAT, 3 } },
} },


{ JOB_VENOM_MAGE, {
    "VM", "Venom Mage",
    0, 7, 5,
    { SP_DEEP_ELF, SP_SPRIGGAN, SP_NAGA, SP_MERFOLK, SP_TENGU, SP_FELID, SP_DEMONSPAWN },
    { "robe", "Young Poisoner's Handbook" },
    weapon_choice::none,
    { { SK_CONJURATIONS, 1 }, { SK_DODGING, 2 }, { SK_POISON_MAGIC, 3 }, { SK_SPELLCASTING, 2 }, { SK_STEALTH, 2 } },
} },


{ JOB_WANDERER, {
    "Wn", "Wanderer",
    0, 0, 0,
    { SP_HILL_ORC, SP_SPRIGGAN, SP_CENTAUR, SP_MERFOLK, SP_BASE_DRACONIAN, SP_HUMAN, SP_DEMONSPAWN },
    {},
    weapon_choice::none,
    {},
} },


{ JOB_WARPER, {
    "Wr", "Warper",
    3, 5, 4,
    { SP_FELID, SP_HALFLING, SP_DEEP_DWARF, SP_SPRIGGAN, SP_CENTAUR, SP_BASE_DRACONIAN },
    { "leather armour", "book of Spatial Translocations", "scroll of blinking", "tomahawk ego:dispersal q:5" },
    weapon_choice::plain,
    { { SK_ARMOUR, 1 }, { SK_DODGING, 2 }, { SK_FIGHTING, 2 }, { SK_SPELLCASTING, 2 }, { SK_THROWING, 1 }, { SK_TRANSLOCATIONS, 3 }, { SK_WEAPON, 2 } },
} },


{ JOB_WIZARD, {
    "Wz", "Wizard",
    -1, 10, 3,
    { SP_DEEP_ELF, SP_NAGA, SP_BASE_DRACONIAN, SP_OCTOPODE, SP_HUMAN, SP_MUMMY },
    { "robe", "hat", "book of Minor Magic" },
    weapon_choice::none,
    { { SK_CONJURATIONS, 1 }, { SK_DODGING, 2 }, { SK_SPELLCASTING, 3 }, { SK_STEALTH, 2 }, { SK_SUMMONINGS, 1 }, { SK_TRANSLOCATIONS, 1 } },
} },

};
