/*
 * This file is autogenerated, see util/job-gen.py and dat/jobs/ for more info.
 */
#pragma once

static job_group job_groups[] =
{

    {
        "Warrior",
        coord_def(0, 0),
        20,
        { JOB_FIGHTER, JOB_GLADIATOR, JOB_MONK, JOB_HUNTER }
    },

    {
        "Adventurer",
        coord_def(0, 7),
        20,
        { JOB_ARTIFICER, JOB_WANDERER, JOB_DELVER, JOB_BRIGAND }
    },

    {
        "Zealot",
        coord_def(1, 0),
        25,
        { JOB_BERSERKER, JOB_ABYSSAL_KNIGHT, JOB_CHAOS_KNIGHT }
    },

    {
        "Warrior-mage",
        coord_def(1, 5),
        26,
        { JOB_SKALD, JOB_TRANSMUTER, JOB_WARPER, JOB_ARCANE_MARKSMAN, JOB_ENCHANTER }
    },

    {
        "Mage",
        coord_def(2, 0),
        22,
        { JOB_WIZARD, JOB_CONJURER, JOB_SUMMONER, JOB_NECROMANCER, JOB_FIRE_ELEMENTALIST, JOB_ICE_ELEMENTALIST, JOB_AIR_ELEMENTALIST, JOB_EARTH_ELEMENTALIST, JOB_VENOM_MAGE }
    },
};
