/*
 * This file is autogenerated, see util/job-gen.py and dat/jobs/ for more info.
 */
#pragma once

#include "macros.h"
#include "tag-version.h"

enum job_type
{
/*
 * These enums are currently hardcoded but should be instead generated by
 * job-gen.py. To do this, once TAG_MAJOR_VERSION is incremented, delete
 * these hardcoded enums and remove `create_enum: false` from the respective
 * job definition files in dat/jobs/.
 */

 //Auto generated enums start here
    JOB_ABYSSAL_KNIGHT,
    JOB_AIR_ELEMENTALIST,
    JOB_ARCANE_MARKSMAN,
    JOB_ARTIFICER,
    JOB_BERSERKER,
    JOB_BRIGAND,
    JOB_CHAOS_KNIGHT,
    JOB_CONJURER,
    JOB_DELVER,
    JOB_EARTH_ELEMENTALIST,
    JOB_ENCHANTER,
    JOB_FIGHTER,
    JOB_FIRE_ELEMENTALIST,
    JOB_GLADIATOR,
    JOB_HUNTER,
    JOB_ICE_ELEMENTALIST,
    JOB_MONK,
    JOB_NECROMANCER,
    JOB_SKALD,
    JOB_SUMMONER,
    JOB_TRANSMUTER,
    JOB_VENOM_MAGE,
    JOB_WANDERER,
    JOB_WARPER,
    JOB_WIZARD,
    NUM_JOBS,

    JOB_UNKNOWN = 100,
    JOB_RANDOM,
    JOB_VIABLE,
};
COMPILE_CHECK(NUM_JOBS < JOB_UNKNOWN);
